const APP_BASE = new URL(".", document.baseURI);
function assetUrl(path){return new URL(String(path).replace(/^\/+/,""),APP_BASE).href}
const ASSET_BASE = assetUrl("public/assets/game").replace(/\/$/,"");
const HERO_ASSET = assetUrl("public/assets/hero/elu-hero-clean.png");
const assets = [
  { id:"ticket", name:"Ticket", meaning:"путь", image:`${ASSET_BASE}/ticket/ticket.png`, tone:"#ffd52a", description:"Маршрут по фестивальному сезону и статус каждой недели." },
  { id:"power-card", name:"Power Card", meaning:"действие", image:`${ASSET_BASE}/power-card/power-card.png`, tone:"#ff2a93", description:"Игровая способность: Second Chance, Mic Drop или Double XP." },
  { id:"access-key", name:"Access Key", meaning:"открытие", image:`${ASSET_BASE}/access-key/access-key.png`, tone:"#29d9ff", description:"Открывает secret mission, bonus event или скрытую награду." },
  { id:"badge", name:"Badge", meaning:"статус", image:`${ASSET_BASE}/badge/badge.png`, tone:"#ffb324", description:"Постоянное достижение за смелость, рост и реальные навыки." },
  { id:"sticker", name:"Sticker", meaning:"самовыражение", image:`${ASSET_BASE}/sticker/sticker.png`, tone:"#ff63ce", description:"Любимый вайб профиля. Можно закрепить до трёх." },
  { id:"drop", name:"Drop", meaning:"сюрприз", image:`${ASSET_BASE}/drop/drop.png`, tone:"#8c52ff", description:"Mystery box с XP, Sticker, Power Card или special Badge." },
  { id:"crew-token", name:"Crew Token", meaning:"вклад", image:`${ASSET_BASE}/crew-token/crew-token.png`, tone:"#b8f516", description:"Награда за помощь команде, feedback и collaboration." },
  { id:"spotlight", name:"Spotlight", meaning:"признание", image:`${ASSET_BASE}/spotlight/spotlight.png`, tone:"#ff7b22", description:"Особое место на сцене за сильный результат или glow-up." }
];

const weeks = [
  {number:1,title:"Who Am I?",mission:"Two Truths & One Lie",asset:"ticket",xp:200,bonus:"Добавь одну деталь, которую никто не знает",bonusXp:40,tone:"#ffd52a"},
  {number:2,title:"English in the Wild",mission:"Найди живой английский вокруг себя",asset:"sticker",xp:220,bonus:"Собери 3 необычных примера",bonusXp:40,tone:"#ff63ce"},
  {number:3,title:"Mystery Case",mission:"Раскрой командную загадку на английском",asset:"access-key",xp:260,bonus:"Объясни одну улику команде",bonusXp:50,tone:"#29d9ff"},
  {number:4,title:"Speak Fest",mission:"Говори 60 секунд на случайную тему",asset:"power-card",xp:300,bonus:"Используй 3 новых выражения",bonusXp:50,tone:"#ff2a93"},
  {number:5,title:"Creator Week",mission:"Создай 30-секундный creative task",asset:"drop",xp:320,bonus:"Добавь неожиданный финал",bonusXp:60,tone:"#8c52ff"},
  {number:6,title:"Real Life Mode",mission:"Пройди roleplay с Plot Twist",asset:"badge",xp:350,bonus:"Не выходи из роли 2 минуты",bonusXp:60,tone:"#ffb324"},
  {number:7,title:"Crew Project",mission:"Создайте один общий проект на четверых",asset:"crew-token",xp:400,bonus:"Помоги teammate улучшить его часть",bonusXp:80,tone:"#b8f516"},
  {number:8,title:"Main Stage",mission:"Выступи 2–3 минуты о том, что тебе интересно",asset:"spotlight",xp:500,bonus:"Ответь на неожиданный вопрос",bonusXp:100,tone:"#ff7b22"}
];

const seedStudents = [
  {id:"alena",name:"Алёна",nickname:"@alena_vibes",initial:"А",level:1,streak:0,longestStreak:0,progress:0,accent:"#ff2a93",stickers:[],featuredBadge:"",spotlight:false,weekStatus:"Not Started",privateNote:"",feedback:"",inventory:[],transactions:[],history:[]},
  {id:"anastasia",name:"Анастасия",nickname:"@anastasia_star",initial:"А",level:1,streak:0,longestStreak:0,progress:0,accent:"#29d9ff",stickers:[],featuredBadge:"",spotlight:false,weekStatus:"Not Started",privateNote:"",feedback:"",inventory:[],transactions:[],history:[]},
  {id:"egor",name:"Егор",nickname:"@egor_power",initial:"Е",level:1,streak:0,longestStreak:0,progress:0,accent:"#b8f516",stickers:[],featuredBadge:"",spotlight:false,weekStatus:"Not Started",privateNote:"",feedback:"",inventory:[],transactions:[],history:[]},
  {id:"kirill",name:"Кирилл",nickname:"@kirill_top",initial:"К",level:1,streak:0,longestStreak:0,progress:0,accent:"#ff7b22",stickers:[],featuredBadge:"",spotlight:false,weekStatus:"Not Started",privateNote:"",feedback:"",inventory:[],transactions:[],history:[]}
];

const seedState = () => ({
  students: structuredClone(seedStudents), currentWeek:1, crewGoal:20000, viewerId:"alena", previewId:null, sound:false,
  effectsMode:"full",particlesEnabled:true,leaderboardEnabled:true,projectName:"ELU LIVE",seasonName:"English Level Up",seasonDates:"сентябрь → осенние каникулы",
  completions:{alena:[],anastasia:[],egor:[],kirill:[]},
  weekRecords:Object.fromEntries(seedStudents.map(s=>[s.id,weeks.map(w=>({week:w.number,status:w.number===1?"Not Started":"Locked",progress:0,asset:null}))])),
  events:[{id:"kickoff",title:"Season Kickoff",date:"Дата будет объявлена",status:"UPCOMING",reward:"First Ticket",icon:"🎟️"}],
  missions:weeks.map(w=>({id:`week-${w.number}`,week:w.number,title:w.title,description:w.mission,instructions:w.bonus,baseXp:w.xp,bonusXp:w.bonusXp,submissionType:"link",active:true,archived:false})),
  feed:[],audit:[]
});

const STORAGE_KEY="elu-live-state-v2";
let state=loadState();
let route="home";
let adminTab="tracker";
let lastUndo=null;
let uploadDraft=null;
const THEME_KEY="elu-theme";
let theme=localStorage.getItem(THEME_KEY)==="light"?"light":"dark";

const navItems=[
  ["home","Главная","i-home"],["challenge","Челлендж","i-zap"],["missions","Миссии","i-target"],["crew","Команда","i-users"],
  ["events","События","i-calendar"],["feed","Лента","i-message"],["leaderboard","Рейтинг","i-trophy"],["profile","Профиль","i-user"]
];

function loadState(){try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)return {...seedState(),...JSON.parse(saved)}}catch(e){console.warn("State could not be loaded",e)}return seedState()}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){toast("Хранилище заполнено. Уменьшите фото.")}}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function assetById(id){return assets.find(a=>a.id===id)}
function studentById(id){return state.students.find(s=>s.id===id)}
function totalXp(student){return student.transactions.reduce((sum,t)=>sum+Number(t.amount),0)}
function rankedStudents(){return [...state.students].sort((a,b)=>totalXp(b)-totalXp(a))}
function crewPower(){return state.students.reduce((sum,s)=>sum+totalXp(s),0)}
function viewer(){return studentById(state.previewId||state.viewerId)||state.students[0]}
function effectsOn(){return state.effectsMode!=="off"}
function fullEffects(){return state.effectsMode==="full"}
function hasStarted(){return state.students.some(s=>totalXp(s)>0||s.progress>0||s.inventory.length>0)}
function addHistory(student,action,detail){student.history.unshift({action,detail,time:new Date().toISOString()});student.history=student.history.slice(0,80)}
function avatarHtml(s,size=""){return `<span class="avatar ${size}" style="--accent:${s.accent}">${s.photo?`<img src="${s.photo}" alt="Фото ${escapeHtml(s.name)}">`:escapeHtml(s.initial)}</span>`}
function icon(id){return `<svg aria-hidden="true"><use href="#${id}"/></svg>`}
function fmt(n){return new Intl.NumberFormat("ru-RU").format(n)}
function clamp(n,min,max){return Math.min(max,Math.max(min,n))}
function statusLabel(value){return ({active:"Активна",locked:"Закрыто",completed:"Выполнено",available:"Доступно","Not Started":"Не начато","In Progress":"В процессе",Submitted:"На проверке","Needs Revision":"Нужна доработка",Completed:"Выполнено",Locked:"Закрыто"})[value]||value}
function assetImg(asset,loading="lazy",className=""){return `<span class="asset-visual ${className}" style="--tone:${asset.tone}"><img src="${asset.image}" alt="${asset.name}" loading="${loading}" width="220" height="220" data-fallback><span class="image-fallback" aria-hidden="true">${asset.name.slice(0,1)}</span></span>`}
function applyTheme(){document.documentElement.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme);document.querySelectorAll(".theme-toggle").forEach(button=>{button.setAttribute("aria-pressed",String(theme==="light"));button.title=theme==="light"?"Включить тёмную тему":"Включить светлую тему";const mark=button.querySelector("span");if(mark)mark.textContent=theme==="light"?"☾":"☀"});const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=theme==="light"?"#eef2ff":"#111a46"}

function renderNav(){
  const main=document.querySelector("#mainNav"),bottom=document.querySelector("#bottomNav");
  main.innerHTML=navItems.map(([id,label,ico])=>`<button class="nav-button ${route===id?"active":""}" data-route="${id}">${icon(ico)}<span>${label}</span></button>`).join("");
  const mobile=navItems.filter(x=>["home","challenge","missions","crew","profile"].includes(x[0]));
  bottom.innerHTML=mobile.map(([id,label,ico])=>`<button class="nav-button ${route===id?"active":""}" data-route="${id}">${icon(ico)}<span>${label}</span></button>`).join("");
}

function renderChrome(){
  const s=viewer();
  document.querySelector("#miniProfile").innerHTML=`${avatarHtml(s)}<span><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.nickname)}</small></span>`;
  document.querySelector("#headerAvatar").innerHTML=s.photo?`<img src="${s.photo}" alt="${escapeHtml(s.name)}">`:escapeHtml(s.initial);
  document.querySelector("#headerXp").textContent=fmt(totalXp(s));document.querySelector("#headerStreak").textContent=s.streak;
  document.querySelector("#xpPill").title=`XP: ${fmt(totalXp(s))}`;document.querySelector("#streakPill").title=`Стрик: ${s.streak} ${pluralDays(s.streak)}`;applyTheme();
  const banner=document.querySelector("#previewBanner");
  if(state.previewId){banner.classList.remove("hidden");banner.innerHTML=`ПРОСМОТР УЧЕНИКА · вы смотрите интерфейс как <strong>${escapeHtml(s.name)}</strong><button data-action="exit-preview">Вернуться в Admin</button>`}else banner.classList.add("hidden");
}

function go(next){route=next;const target=next==="home"?new URL(".",APP_BASE):new URL(`#${next}`,APP_BASE);history.replaceState(null,"",target);render()}
function render(){renderNav();renderChrome();applyPreferences();const view=document.querySelector("#view");const renderer={home:renderHome,challenge:renderChallenge,missions:renderMissions,crew:renderCrew,events:renderEvents,leaderboard:renderLeaderboard,feed:renderFeed,profile:renderProfile,admin:renderAdmin}[route]||renderHome;view.innerHTML=`<div class="page-enter">${renderer()}</div>`;view.focus({preventScroll:true});requestAnimationFrame(setupEnhancements)}

function weekState(w){if((state.completions[viewer().id]||[]).includes(w.number))return "completed";if(w.number===state.currentWeek)return "active";if(w.number>state.currentWeek)return "locked";return "available"}
function roadmapHtml(){return `<div class="roadmap">${weeks.map(w=>{const a=assetById(w.asset),st=weekState(w);return `<button class="week-card mechanic-${w.asset} ${st}" style="--theme:${w.tone}" data-action="view-week" data-week="${w.number}" aria-label="Неделя ${w.number}: ${w.title}, ${statusLabel(st)}"><small>WEEK ${w.number}</small>${assetImg(a)}<strong>${w.title}</strong><span>${a.name} · ${statusLabel(st)}</span></button>`}).join("")}</div>`}

function studentCard(s,index){const started=hasStarted(),xp=totalXp(s);return `<article class="student-card tilt-card" data-student="${s.id}" style="--accent:${s.accent}" tabindex="0" role="button" aria-label="Открыть профиль ${escapeHtml(s.name)}">${started&&xp>0?`<div class="rank">${rankedStudents().findIndex(x=>x.id===s.id)+1}</div>`:""}<div class="student-top">${avatarHtml(s)}<div class="student-name"><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.nickname)}</small></div></div><div class="badgeline"><span class="level-chip">B1 · Level ${s.level}</span><span class="xp-label" data-counter="${xp}">${fmt(xp)} XP</span></div><div class="streak ${s.streak>0?'is-live':''}">Стрик: ${s.streak} ${pluralDays(s.streak)}${s.streak>0?' 🔥':''}</div><div class="progress-label"><span>Week ${state.currentWeek} · ${s.progress===0?'Можно начинать':statusLabel(s.weekStatus)}</span><b>${s.progress}%</b></div><div class="progress" style="--progress:${s.progress}%"><i></i></div><div class="sticker-row">${s.stickers.length?s.stickers.slice(0,3).map((x,i)=>`<span class="sticker" style="--rot:${i%2?2:-2}deg">${escapeHtml(x)}</span>`).join(""):'<span class="empty-chip">Наград пока нет</span>'}</div></article>`}
function pluralDays(n){const d=n%10;return d===1?"день":d>1&&d<5?"дня":"дней"}
function sectionHead(title,sub="",action=""){return `<div class="section-head"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:""}</div>${action}</div>`}
function leaderList(){if(!hasStarted())return `<div class="zero-state"><span>✦</span><strong>Все начинают с одной позиции</strong><small>Рейтинг появится после первых XP</small></div>`;return rankedStudents().map((s,i)=>`<div class="leader-row ${i===0?'leader-first':''}"><i>${i+1}</i><span>${escapeHtml(s.name)}</span><b>${fmt(totalXp(s))} XP</b></div>`).join("")}
function feedList(limit=9){if(!state.feed.length)return `<div class="zero-state"><span>⚡</span><strong>Сезон только начинается</strong><small>Первые события появятся здесь</small></div>`;return state.feed.slice(0,limit).map(f=>`<div class="feed-item reveal"><span class="feed-icon">${f.icon}</span><span>${escapeHtml(f.text)}</span><time>${escapeHtml(f.time)}</time></div>`).join("")}

function renderHome(){
 const s=viewer(),w=weeks[state.currentWeek-1],crew=crewPower(),pct=clamp(crew/state.crewGoal*100,0,100),earned=s.inventory.slice(0,4);
 return `<section class="hero animated-stage" style="--hero-image:url('${HERO_ASSET}')"><div class="hero-media"><div class="hero-poster" role="img" aria-label="Неоновая фестивальная сцена и зрители"></div><div class="stage-vignette"></div><i class="light-beam beam-one"></i><i class="light-beam beam-two"></i><i class="light-beam beam-three"></i><div class="hero-particles" aria-hidden="true">${Array.from({length:16},(_,i)=>`<i style="--i:${i}"></i>`).join("")}</div><div class="hero-doodles" aria-hidden="true"><b>⚡</b><b>♕</b><b>★</b><b>♫</b><b>➜</b></div></div><div class="hero-copy"><div class="eyebrow hero-eyebrow">8-недельный челлендж B1</div><h1><span class="hero-english">English</span><br><span class="lime hero-level">Level Up</span></h1><div class="hero-tagline">Speak. Learn. Shine.</div><div class="hero-sub hero-subtitle"><span>Week ${w.number} · ${w.title}</span><span>${escapeHtml(state.seasonDates)}</span></div><div class="hero-actions"><button class="btn btn-primary cta-live" data-action="start-mission">▶ НАЧАТЬ МИССИЮ</button><button class="btn btn-secondary" data-route="challenge">Смотреть roadmap →</button></div></div></section>
 ${sectionHead("Твой путь к Main Stage","8 недель · 8 механик · один crew","<button class='link-button' data-route='challenge'>Все недели →</button>")}${roadmapHtml()}
 <div class="dashboard-grid"><div class="content-stack">${sectionHead("Crew ready","Четыре участника · все начинают с нуля")}<div class="student-grid">${state.students.map(studentCard).join("")}</div><article class="panel mission-card" style="--mission-asset:url('${assetById(w.asset).image}')"><div class="eyebrow">⚡ Текущая неделя</div><div class="mission-title">Week ${w.number} — ${w.title}</div><div class="mission-main"><small>ГЛАВНАЯ МИССИЯ</small><strong>${w.mission}</strong></div><div class="mission-rewards"><div class="reward-box"><b>SECRET BONUS +${w.bonusXp} XP</b>${w.bonus}</div><div class="reward-box"><b>НАГРАДА +${w.xp} XP</b>${assetById(w.asset).name}</div></div><button class="btn btn-primary cta-live" data-action="start-mission">Начать миссию ⚡</button></article>
 <div class="feed-grid"><article class="panel collection-preview"><h3>Моя коллекция</h3>${earned.length?`<div class="asset-strip">${earned.map(id=>{const a=assetById(id);return `<button class="asset-mini" data-asset="${a.id}">${assetImg(a)}<span>${a.name}</span></button>`}).join("")}</div>`:`<div class="zero-state compact"><span>◇</span><strong>Первые награды ещё впереди</strong><small>Они появятся после выполнения миссий</small></div>`}<button class="link-button" data-route="profile">Все награды в профиле →</button></article><article class="panel"><h3>Лента команды</h3><div class="feed-list">${feedList(3)}</div></article></div></div>
 <aside class="side-stack"><article class="panel crew-panel"><h3>⚡ Crew Power</h3><div class="crew-number">${fmt(crew)} <small>/ ${fmt(state.crewGoal)} XP</small></div><div class="milestones"><span>0</span><span>5K</span><span>10K</span><span>15K</span><span>20K</span></div><div class="progress crew-progress" style="--progress:${pct}%"><i></i></div><p>Заполняйте шкалу всей командой и открывайте общий бонус.</p></article><article class="panel event-card"><div class="eyebrow">● UPCOMING</div><h3>Season Kickoff</h3><div class="event-row"><span class="event-icon">🎟️</span><div><strong>First Ticket</strong><small>Дата будет объявлена</small></div></div></article>${state.leaderboardEnabled?`<article class="panel"><h3>🏆 Рейтинг</h3><div class="leader-list">${leaderList()}</div></article>`:""}</aside></div>`
}

function pageHeader(title,sub,action=""){return `<div class="page-header"><div><h1 class="page-title">${title}</h1><p>${sub}</p></div>${action}</div>`}
function renderChallenge(){return `${pageHeader("8-week challenge","Восемь недель · восемь наград · один Main Stage")}<div class="challenge-grid">${weeks.map(w=>{const a=assetById(w.asset),st=weekState(w);return `<article class="week-card big-week mechanic-${w.asset} ${st}" style="--theme:${w.tone}"><span class="state-label">${st==="locked"?'🔒 ':st==="completed"?'✓ ':''}${statusLabel(st)}</span><small>WEEK ${w.number}</small>${assetImg(a)}<h3>${w.title}</h3><p>${w.mission}</p><div class="week-reward">Награда: +${w.xp} XP · ${a.name}</div><button class="btn ${st==="locked"?"btn-secondary":"btn-primary"} btn-compact" ${st==="locked"?"disabled":""} data-action="view-week" data-week="${w.number}">${st==="locked"?"Неделя закрыта":"Открыть миссию →"}</button></article>`}).join("")}</div>`}
function renderMissions(){const w=weeks[state.currentWeek-1];return `${pageHeader("Missions","Текущая миссия — сначала. Без перегруза.")}<div class="dashboard-grid"><div><article class="panel mission-card" style="--mission-asset:url('${assetById(w.asset).image}')"><div class="eyebrow">Now playing · Week ${w.number}</div><div class="mission-title">${w.title}</div><div class="mission-main"><small>ГЛАВНАЯ МИССИЯ</small><strong>${w.mission}</strong></div><div class="mission-rewards"><div class="reward-box"><b>SECRET BONUS +${w.bonusXp} XP</b>${w.bonus}</div><div class="reward-box"><b>REWARD</b>${assetById(w.asset).name} · +${w.xp} XP</div></div><button class="btn btn-primary cta-live" data-action="start-mission">▶ Start mission</button></article></div><aside class="panel"><h3>Твой статус</h3><div class="stat-card"><span>Progress</span><strong style="--tone:${viewer().accent}">${viewer().progress}%</strong><div class="progress" style="--progress:${viewer().progress}%"><i></i></div></div><p style="font-size:11px;color:var(--muted);line-height:1.6">После отправки преподаватель проверит миссию. XP и ассет появятся автоматически.</p></aside></div>`}
function renderCrew(){const crew=crewPower(),pct=clamp(crew/state.crewGoal*100,0,100);return `${pageHeader("Crew Power","Level up together · поддержка тоже считается")}<div class="stats-grid"><div class="stat-card"><span>Участников</span><strong>4</strong></div><div class="stat-card"><span>Всего XP</span><strong>${fmt(crew)}</strong></div><div class="stat-card"><span>Миссий закрыто</span><strong>${Object.values(state.completions).flat().length}</strong></div><div class="stat-card"><span>Crew goal</span><strong>${Math.round(pct)}%</strong></div></div>${sectionHead("Участники","Crew Token выдаётся за реальный вклад")}<div class="student-grid">${rankedStudents().map(studentCard).join("")}</div>${sectionHead("Crew milestones")}<article class="panel crew-panel"><div class="crew-number">${fmt(crew)} <small>/ ${fmt(state.crewGoal)} XP</small></div><div class="progress" style="--progress:${pct}%"><i></i></div><div class="milestones" style="font-size:11px"><span>5K · Sticker pack</span><span>10K · Access Key</span><span>15K · Secret Event</span><span>20K · Crew Drop</span></div></article>`}
function renderEvents(){return `${pageHeader("Live events","События сезона и путь к Main Stage")}<div class="events-grid">${state.events.map((e,i)=>`<article class="panel event-card"><div class="event-row"><span class="event-icon">${e.icon}</span><div><div class="eyebrow">${e.status}</div><h2>${escapeHtml(e.title)}</h2><small>${escapeHtml(e.date)}</small></div></div><p>Награда · ${escapeHtml(e.reward)}</p>${i===0?`<button class="btn btn-primary btn-compact" data-action="event-info" data-id="${e.id}">Подробнее</button>`:`<span class="info-chip">🔒 Закрыто</span>`}</article>`).join("")}</div>`}
function renderLeaderboard(){return `${pageHeader("Рейтинг","Все начинают с одной позиции")}<div class="tabs" aria-label="Доступные виды рейтинга"><span class="tab active">Total XP</span><span class="tab">Weekly XP · скоро</span><span class="tab">Streak · скоро</span><span class="tab">Teamwork · скоро</span></div><article class="panel" style="margin-top:13px"><div class="leader-list">${hasStarted()?rankedStudents().map((s,i)=>`<div class="leader-row ${i===0?'leader-first':''}" style="grid-template-columns:34px 52px 1fr auto;padding:11px;border-bottom:1px solid var(--line)"><i>${i+1}</i>${avatarHtml(s)}<span><strong style="display:block">${escapeHtml(s.name)}</strong><small>${escapeHtml(s.featuredBadge||'Можно начинать')}</small></span><b>${fmt(totalXp(s))} XP</b></div>`).join(""):leaderList()}</div></article>`}
function renderFeed(){return `${pageHeader("Crew feed","Живой сезон без публичных комментариев")}<article class="panel"><div class="feed-list">${feedList()}</div></article>`}
function renderProfile(){const s=viewer(),rank=hasStarted()&&totalXp(s)>0?`#${rankedStudents().findIndex(x=>x.id===s.id)+1}`:"—";return `${pageHeader("Профиль","Твой сезон, награды и прогресс")}<article class="panel profile-hero" style="--accent:${s.accent}">${avatarHtml(s)}<div class="profile-name"><h1>${escapeHtml(s.name)}</h1><p>${escapeHtml(s.nickname)} · B1 · Level ${s.level}</p><div class="sticker-row">${s.stickers.length?s.stickers.map(x=>`<span class="sticker">${escapeHtml(x)}</span>`).join(""):'<span class="empty-chip">Награды появятся после первых миссий</span>'}</div></div><div class="profile-stats"><div class="profile-stat"><span>Total XP</span><b>${fmt(totalXp(s))}</b></div><div class="profile-stat"><span>Стрик</span><b>${s.streak}${s.streak?' 🔥':''}</b></div><div class="profile-stat"><span>Позиция</span><b>${rank}</b></div></div></article><div class="profile-layout"><article class="panel"><h3>Прогресс сезона</h3><div class="season-list">${weeks.map(w=>{const done=(state.completions[s.id]||[]).includes(w.number),active=w.number===state.currentWeek;return `<div class="season-row"><strong>${w.number}</strong><span>${w.title}<small>${w.mission}</small></span><div class="progress" style="--progress:${done?100:active?s.progress:0}%"><i></i></div><b>${statusLabel(done?'completed':active?s.weekStatus:'locked')}</b></div>`}).join("")}</div></article><aside class="content-stack"><article class="panel rewards-panel"><h3>Моя коллекция</h3>${s.inventory.length?`<div class="reward-collection">${s.inventory.map(id=>{const a=assetById(id);return `<button class="asset-mini" data-asset="${id}">${assetImg(a)}<span>${a.name}</span></button>`}).join("")}</div>`:`<div class="zero-state reward-empty">${assetImg(assetById('ticket'))}<strong>Твои первые награды появятся после выполнения миссий.</strong><small>Начни Week 1, чтобы открыть Ticket</small></div>`}</article>${s.featuredBadge?`<article class="panel"><h3>Featured Badge</h3><div class="featured-reward">${assetImg(assetById('badge'))}<div><strong>${escapeHtml(s.featuredBadge)}</strong><p>Особая награда сезона</p></div></div></article>`:""}${s.feedback?`<article class="panel"><h3>Комментарий преподавателя</h3><p>${escapeHtml(s.feedback)}</p></article>`:""}</aside></div>`}

function renderAdmin(){const tabs=[["tracker","Трекер"],["matrix","Матрица 8 недель"],["lesson","Режим урока"],["missions","Миссии"],["assets","Награды"],["events","События"],["audit","Журнал"],["media","Медиа"],["settings","Настройки"]];return `<section class="admin-shell"><header class="admin-bar"><div><h1>ELU Control Room</h1><p>Управление челленджем и прогрессом группы</p><span class="demo-note"><b>DEMO ADMIN</b> · данные хранятся локально в браузере</span></div><div class="admin-actions"><button class="btn btn-secondary btn-compact" data-action="preview-menu">${icon('i-eye')} Preview as Student</button><button class="icon-btn theme-toggle" data-action="toggle-theme" aria-label="Переключить тему"><span aria-hidden="true">${theme==="light"?'☾':'☀'}</span></button><button class="btn btn-primary btn-compact" data-route="home">Student App →</button></div></header><div class="admin-content"><nav class="admin-tabs">${tabs.map(([id,label])=>`<button class="admin-tab ${adminTab===id?'active':''}" data-admin-tab="${id}">${label}</button>`).join("")}</nav>${renderAdminTab()}</div></section>`}
function renderAdminTab(){
 if(adminTab==="matrix")return renderMatrix();
 if(adminTab==="lesson")return renderLessonMode();
 if(adminTab==="missions")return renderMissionManager();
 if(adminTab==="assets")return `${pageHeader("Игровые награды","Восемь механик сезона")}<div class="assets-grid admin-assets">${assets.map(a=>`<article class="panel asset-card">${assetImg(a)}<h3>${a.name}</h3><p>${a.description}</p><span class="rarity">ACTIVE · EPIC</span></article>`).join("")}</div>`;
 if(adminTab==="events")return `${pageHeader("События","Каталог событий сезона")}<div class="events-grid">${state.events.map(e=>`<article class="panel event-card"><div class="event-row"><span class="event-icon">${e.icon}</span><div><h2>${escapeHtml(e.title)}</h2><small>${escapeHtml(e.date)}</small></div></div><p>${escapeHtml(e.reward)}</p><span class="info-chip">${escapeHtml(e.status)}</span></article>`).join("")}</div>`;
 if(adminTab==="audit")return `${pageHeader("Audit log","Every important local prototype change")}${state.audit.length?`<div class="audit-list">${state.audit.map(a=>`<div class="audit-item"><strong>${escapeHtml(a.action)}</strong><p>${escapeHtml(a.detail)}</p><code>Before: ${escapeHtml(a.before||'—')} · After: ${escapeHtml(a.after||a.detail)}</code><time>${new Date(a.time).toLocaleString('ru-RU')}</time></div>`).join("")}</div>`:'<div class="zero-state"><span>↺</span><strong>No admin changes yet</strong><small>История появится после первого действия</small></div>'}`;
 if(adminTab==="media")return `${pageHeader("Media library","Локальный prototype: фотографии оптимизируются и сохраняются только в этом браузере")}<div class="student-grid">${state.students.map(s=>`<article class="student-card" style="--accent:${s.accent}">${avatarHtml(s)}<h3>${escapeHtml(s.name)}</h3><button class="btn btn-secondary btn-compact" data-action="photo" data-id="${s.id}">${icon('i-upload')} ${s.photo?'Заменить фото':'Загрузить фото'}</button>${s.photo?`<button class="btn btn-danger btn-compact" data-action="remove-photo" data-id="${s.id}">Удалить</button>`:''}</article>`).join("")}</div>`;
 if(adminTab==="settings")return renderSettings();
 return renderTracker();
}
function renderTracker(){const pending=state.students.filter(s=>s.weekStatus==="Submitted").length,crew=crewPower();return `<div class="admin-kpis"><div class="admin-kpi"><small>CREW POWER</small><strong>${fmt(crew)} XP</strong></div><div class="admin-kpi"><small>НА ПРОВЕРКЕ</small><strong>${pending}</strong></div><div class="admin-kpi"><small>ТЕКУЩАЯ НЕДЕЛЯ</small><strong>${state.currentWeek} / 8</strong></div><div class="admin-kpi"><small>ВЫПОЛНЕНО МИССИЙ</small><strong>${Object.values(state.completions).flat().length}</strong></div></div><div class="table-wrap"><table class="tracker"><thead><tr><th>Ученик</th><th>Неделя</th><th>Статус</th><th>XP</th><th>Стрик</th><th>Прогресс</th><th>Награды</th><th>Quick Update</th></tr></thead><tbody>${state.students.map(s=>`<tr><td class="sticky-student"><label class="student-select"><input type="checkbox" data-select-student="${s.id}"><button class="student-cell link-button" data-student="${s.id}">${avatarHtml(s)}<span><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.nickname)}</small></span></button></label></td><td>W${state.currentWeek}<small>${escapeHtml(weeks[state.currentWeek-1].title)}</small></td><td><select data-field="weekStatus" data-id="${s.id}" aria-label="Статус ${escapeHtml(s.name)}">${["Not Started","In Progress","Submitted","Needs Revision","Completed"].map(v=>`<option value="${v}" ${s.weekStatus===v?'selected':''}>${statusLabel(v)}</option>`).join("")}</select></td><td><b>${fmt(totalXp(s))}</b></td><td>${s.streak} ${pluralDays(s.streak)}</td><td><input data-field="progress" data-id="${s.id}" aria-label="Прогресс ${escapeHtml(s.name)}" type="number" min="0" max="100" value="${s.progress}">%</td><td>${s.inventory.length}</td><td><button class="btn btn-secondary btn-compact" data-student="${s.id}">Открыть</button></td></tr>`).join("")}</tbody></table></div><div class="bulk-bar"><strong>Групповые действия</strong><button data-action="bulk-complete">Выполнено</button><button data-action="bulk-xp">Добавить XP</button><button data-action="bulk-asset">Выдать награду</button><button data-action="bulk-reset">Сбросить статус</button></div>`}
function renderMatrix(){return `${pageHeader("Матрица 8 недель","Нажмите ячейку, чтобы открыть Quick Update")}<div class="table-wrap"><table class="tracker matrix"><thead><tr><th>Ученик</th>${weeks.map(w=>`<th>W${w.number}<small>${w.title}</small></th>`).join("")}</tr></thead><tbody>${state.students.map(s=>`<tr><td class="sticky-student"><button class="student-cell link-button" data-student="${s.id}">${avatarHtml(s)}<span><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.nickname)}</small></span></button></td>${state.weekRecords[s.id].map(r=>`<td><button class="matrix-cell ${r.status.toLowerCase().replaceAll(' ','-')}" data-action="matrix-cell" data-id="${s.id}" data-week="${r.week}">${r.status==="Locked"?'🔒 ':r.status==="Completed"?'✓ ':r.status==="In Progress"?'◐ ':'○ '}${statusLabel(r.status)}</button></td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function renderLessonMode(){const w=weeks[state.currentWeek-1];return `${pageHeader("Режим урока",`Week ${w.number} · ${w.title}`,`<select class="form-control lesson-week" data-setting="currentWeek">${weeks.map(x=>`<option value="${x.number}" ${x.number===w.number?'selected':''}>Week ${x.number} · ${x.title}</option>`).join("")}</select>`)}<article class="panel lesson-hero"><div><div class="eyebrow">БЫСТРЫЙ РЕЖИМ ПРЕПОДАВАТЕЛЯ</div><h2>${w.mission}</h2><p>Выполнено → +${w.xp} XP → выдать ${assetById(w.asset).name}</p></div>${assetImg(assetById(w.asset))}</article><div class="lesson-grid">${state.students.map(s=>`<article class="panel lesson-student">${avatarHtml(s)}<div><h3>${escapeHtml(s.name)}</h3><small>${statusLabel(s.weekStatus)} · ${fmt(totalXp(s))} XP</small></div><div class="lesson-actions"><button class="btn btn-lime btn-compact" data-action="complete" data-id="${s.id}">✓ Выполнено</button><button class="btn btn-secondary btn-compact" data-action="xp-modal" data-id="${s.id}">+ XP</button><button class="btn btn-secondary btn-compact" data-action="asset-modal" data-id="${s.id}">Выдать награду</button><button class="btn btn-secondary btn-compact" data-student="${s.id}">Заметка</button></div></article>`).join("")}</div>`}
function renderMissionManager(){return `${pageHeader("Missions CRUD","Create, edit, duplicate, hide or archive","<button class='btn btn-primary btn-compact' data-action='new-mission'>+ New mission</button>")}<div class="mission-admin-list">${state.missions.map(m=>`<article class="panel mission-admin-row"><span class="level-chip">W${m.week}</span><div><strong>${escapeHtml(m.title)}</strong><small>${escapeHtml(m.description)} · ${m.baseXp} XP</small></div><span class="rarity">${m.archived?'ARCHIVED':m.active?'ACTIVE':'HIDDEN'}</span><div class="quick-buttons"><button data-action="edit-mission" data-id="${m.id}">Edit</button><button data-action="duplicate-mission" data-id="${m.id}">Duplicate</button><button data-action="toggle-mission" data-id="${m.id}">${m.active?'Hide':'Show'}</button></div></article>`).join("")}</div>`}
function renderSettings(){return `${pageHeader("Настройки сезона","Бренд, прогресс и визуальные эффекты")}<div class="settings-note"><b>DEMO ADMIN</b><span>Для production требуется server-side authorization, database и private storage.</span></div><div class="form-grid"><div class="form-field"><label>Название проекта</label><input class="form-control" value="${escapeHtml(state.projectName)}" data-setting="projectName"></div><div class="form-field"><label>Сезон</label><input class="form-control" value="${escapeHtml(state.seasonName)}" data-setting="seasonName"></div><div class="form-field"><label>Даты сезона</label><input class="form-control" value="${escapeHtml(state.seasonDates)}" data-setting="seasonDates"></div><div class="form-field"><label>Текущая неделя</label><select class="form-control" data-setting="currentWeek">${weeks.map(w=>`<option value="${w.number}" ${w.number===state.currentWeek?'selected':''}>Week ${w.number} · ${w.title}</option>`).join("")}</select></div><div class="form-field"><label>Crew Power goal</label><input class="form-control" type="number" min="1000" step="500" value="${state.crewGoal}" data-setting="crewGoal"></div><div class="form-field"><label>Тема</label><select class="form-control" data-setting="theme"><option value="dark" ${theme==='dark'?'selected':''}>Dark</option><option value="light" ${theme==='light'?'selected':''}>Light</option></select></div><div class="form-field"><label>Эффекты</label><select class="form-control" data-setting="effectsMode"><option value="full" ${state.effectsMode==='full'?'selected':''}>Full</option><option value="reduced" ${state.effectsMode==='reduced'?'selected':''}>Reduced</option><option value="off" ${state.effectsMode==='off'?'selected':''}>Off</option></select></div>${[["particlesEnabled","Частицы"],["leaderboardEnabled","Рейтинг"]].map(([key,label])=>`<div class="form-field"><label>${label}</label><select class="form-control" data-setting="${key}"><option value="true" ${state[key]?'selected':''}>On</option><option value="false" ${!state[key]?'selected':''}>Off</option></select></div>`).join("")}<div class="form-field full danger-zone"><label>Опасная зона</label><p>Сброс удалит прогресс, XP, стрики, награды и активность. Имена и фото сохранятся.</p><button class="btn btn-danger" data-action="reset-season">Reset Season</button></div></div>`}

function commit(action,detail,mutator){const before=JSON.stringify(state),beforeLabel=`XP ${crewPower()} · completions ${Object.values(state.completions).flat().length}`;mutator();const afterLabel=`XP ${crewPower()} · completions ${Object.values(state.completions).flat().length}`;state.audit.unshift({action,detail,before:beforeLabel,after:afterLabel,time:new Date().toISOString()});state.audit=state.audit.slice(0,80);saveState();lastUndo=()=>{state=JSON.parse(before);saveState();render();toast("↩ Change undone")};render();toast(detail,true)}
function toast(message,undo=false){const root=document.querySelector("#toastRoot"),el=document.createElement("div");el.className="toast";el.innerHTML=`<strong>✓</strong> ${escapeHtml(message)} ${undo?'<button data-action="undo">Undo</button>':''}`;root.append(el);setTimeout(()=>el.remove(),undo?8000:3500)}
function burstXp(amount,element){if(!effectsOn())return;const box=element?.getBoundingClientRect(),el=document.querySelector("#xpBurst");el.textContent=`${amount>0?'+':''}${amount} XP`;el.style.left=`${box?box.left+box.width/2:innerWidth/2}px`;el.style.top=`${box?box.top:innerHeight/2}px`;el.classList.remove("show");void el.offsetWidth;el.classList.add("show")}
function confetti(){if(!fullEffects())return;const layer=document.createElement("div");layer.className="confetti";for(let i=0;i<28;i++){const p=document.createElement("i");p.style.setProperty("--c",["#ff2a93","#29d9ff","#b8f516","#ffd52a"][i%4]);p.style.setProperty("--dx",`${(Math.random()-.5)*500}px`);p.style.setProperty("--dy",`${(Math.random()-.35)*420}px`);p.style.left=`${40+Math.random()*20}%`;p.style.animationDelay=`${Math.random()*.18}s`;layer.append(p)}document.body.append(layer);setTimeout(()=>layer.remove(),1300)}

function openStudent(id,week=state.currentWeek){
 const s=studentById(id),record=state.weekRecords[s.id][week-1],weekInfo=weeks[week-1];
 document.querySelector("#modalRoot").innerHTML=`<div class="drawer-backdrop" data-action="close-overlay"><aside class="drawer" role="dialog" aria-modal="true" aria-label="Quick Update ${escapeHtml(s.name)}" onclick="event.stopPropagation()">
  <div class="drawer-head">${avatarHtml(s)}<div><div class="eyebrow">QUICK UPDATE · WEEK ${week}</div><h2>${escapeHtml(s.name)}</h2><p>${escapeHtml(s.nickname)} · B1 · ${fmt(totalXp(s))} XP</p><small>Week ${week} · ${escapeHtml(weekInfo.title)}</small></div><button class="close-button" data-action="close-overlay" aria-label="Закрыть">×</button></div>
  <div class="drawer-section"><div class="form-grid"><div class="form-field"><label>Имя</label><input class="form-control" id="studentName" value="${escapeHtml(s.name)}"></div><div class="form-field"><label>Никнейм</label><input class="form-control" id="studentNick" value="${escapeHtml(s.nickname)}"></div><div class="form-field"><label>Статус</label><select class="form-control" id="studentStatus">${["Not Started","In Progress","Submitted","Needs Revision","Completed","Locked"].map(v=>`<option value="${v}" ${record.status===v?'selected':''}>${statusLabel(v)}</option>`).join("")}</select></div><div class="form-field"><label>Прогресс %</label><input class="form-control" id="studentProgress" type="number" min="0" max="100" value="${record.progress}"></div><div class="form-field full"><label>Приватная заметка преподавателя</label><textarea class="form-control" id="studentPrivateNote">${escapeHtml(s.privateNote||'')}</textarea></div><div class="form-field full"><label>Комментарий для ученика</label><textarea class="form-control" id="studentFeedback">${escapeHtml(s.feedback||'')}</textarea></div></div><div class="modal-actions"><button class="btn btn-secondary" data-action="photo" data-id="${s.id}">${icon('i-upload')} Сменить фото</button><button class="btn btn-primary" data-action="save-student" data-id="${s.id}" data-week="${week}">Сохранить</button></div></div>
  <div class="drawer-section"><h3>Быстрый XP · причина обязательна</h3><div class="quick-buttons"><button data-action="xp-modal" data-id="${s.id}" data-amount="10">+10</button><button data-action="xp-modal" data-id="${s.id}" data-amount="20">+20</button><button data-action="xp-modal" data-id="${s.id}" data-amount="50">+50</button><button data-action="xp-modal" data-id="${s.id}" data-amount="100">+100</button><button data-action="xp-modal" data-id="${s.id}">Другая сумма</button><button data-action="xp-modal" data-id="${s.id}" data-amount="-10">− XP</button></div></div>
  <div class="drawer-section"><h3>Стрик</h3><div class="quick-buttons"><button data-action="streak-add" data-id="${s.id}">+1 день</button><button data-action="streak-custom" data-id="${s.id}">Изменить</button><button data-action="streak-reset" data-id="${s.id}">Сбросить</button></div></div>
  <div class="drawer-section"><h3>Миссия и награды</h3><div class="quick-buttons"><button data-action="complete" data-id="${s.id}" data-week="${week}">✓ Завершить Week ${week}</button><button data-action="asset-modal" data-id="${s.id}">Выдать награду</button></div></div>
  <div class="drawer-section"><h3>История</h3>${s.history.length?`<div class="audit-list">${s.history.map(h=>`<div class="audit-item"><strong>${escapeHtml(h.action)}</strong><p>${escapeHtml(h.detail)}</p><time>${new Date(h.time).toLocaleString('ru-RU')}</time></div>`).join("")}</div>`:'<div class="zero-state"><small>История появится после первых изменений</small></div>'}</div>
  <div class="drawer-section"><h3>XP-транзакции</h3>${s.transactions.length?`<div class="audit-list">${[...s.transactions].reverse().map(t=>`<div class="audit-item"><strong style="color:${t.amount>=0?'var(--lime)':'var(--danger)'}">${t.amount>=0?'+':''}${t.amount} XP</strong><p>${escapeHtml(t.reason)}</p><time>${new Date(t.date).toLocaleString('ru-RU')}</time></div>`).join("")}</div>`:'<div class="zero-state"><small>0 XP · транзакций пока нет</small></div>'}</div>
 </aside></div>`
}

function openXpModal(id,preset=""){const s=studentById(id);document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop" data-action="close-overlay"><div class="modal compact-modal" onclick="event.stopPropagation()"><div class="modal-head"><div><div class="eyebrow">XP TRANSACTION</div><h2>${escapeHtml(s.name)}</h2></div><button class="close-button" data-action="close-overlay">×</button></div><div class="form-grid"><div class="form-field"><label>Amount</label><input class="form-control" id="xpAmount" type="number" value="${preset}" placeholder="100"></div><div class="form-field"><label>Week</label><select class="form-control" id="xpWeek">${weeks.map(w=>`<option value="${w.number}" ${w.number===state.currentWeek?'selected':''}>Week ${w.number}</option>`).join("")}</select></div><div class="form-field full"><label>Reason *</label><select class="form-control" id="xpReason"><option value="">Choose reason</option><option>Main Mission</option><option>Secret Bonus</option><option>Great Speaking</option><option>Crew Contribution</option><option>Teacher Bonus</option><option>Correction</option></select></div></div><div class="modal-actions"><button class="btn btn-secondary" data-action="close-overlay">Cancel</button><button class="btn btn-primary" data-action="save-xp" data-id="${id}">Save transaction</button></div></div></div>`}
function openAssetPicker(id){const s=studentById(id);document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop" data-action="close-overlay"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><div><div class="eyebrow">ВЫДАТЬ НАГРАДУ</div><h2>${escapeHtml(s.name)}</h2></div><button class="close-button" data-action="close-overlay">×</button></div><div class="asset-picker">${assets.map(a=>`<button data-action="grant-asset" data-id="${id}" data-asset-id="${a.id}" style="--tone:${a.tone}">${assetImg(a)}<strong>${a.name}</strong><small>${a.meaning}</small></button>`).join("")}</div></div></div>`}
function openResetSeason(){document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop" data-action="close-overlay"><div class="modal compact-modal" onclick="event.stopPropagation()"><div class="modal-head"><div><div class="eyebrow">DANGER ZONE</div><h2>Reset Season</h2></div><button class="close-button" data-action="close-overlay">×</button></div><p>XP, streaks, missions, assets, Feed и Crew Power вернутся к нулю. Фото и профили сохранятся.</p><div class="form-field"><label>Введите RESET SEASON</label><input class="form-control" id="resetPhrase" autocomplete="off"></div><div class="modal-actions"><button class="btn btn-secondary" data-action="close-overlay">Cancel</button><button class="btn btn-danger" data-action="confirm-reset-season">Reset Season</button></div></div></div>`}
function openMissionEditor(id=null){const m=id?state.missions.find(x=>x.id===id):{id:"",week:state.currentWeek,title:"",description:"",instructions:"",baseXp:100,bonusXp:0,submissionType:"link",active:true};document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop" data-action="close-overlay"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h2>${id?'Edit':'Create'} mission</h2><button class="close-button" data-action="close-overlay">×</button></div><div class="form-grid"><div class="form-field"><label>Week</label><input class="form-control" id="missionWeek" type="number" min="1" max="8" value="${m.week}"></div><div class="form-field"><label>Base XP</label><input class="form-control" id="missionXp" type="number" value="${m.baseXp}"></div><div class="form-field full"><label>Title</label><input class="form-control" id="missionTitle" value="${escapeHtml(m.title)}"></div><div class="form-field full"><label>Description</label><textarea class="form-control" id="missionDescription">${escapeHtml(m.description)}</textarea></div><div class="form-field full"><label>Instructions / bonus</label><textarea class="form-control" id="missionInstructions">${escapeHtml(m.instructions)}</textarea></div><div class="form-field"><label>Bonus XP</label><input class="form-control" id="missionBonusXp" type="number" value="${m.bonusXp}"></div><div class="form-field"><label>Submission type</label><select class="form-control" id="missionSubmission">${["text","audio","image","file","link"].map(x=>`<option ${m.submissionType===x?'selected':''}>${x}</option>`).join("")}</select></div></div><div class="modal-actions"><button class="btn btn-secondary" data-action="close-overlay">Cancel</button><button class="btn btn-primary" data-action="save-mission" data-id="${m.id}">Save mission</button></div></div></div>`}
function openAsset(id){const a=assetById(id),interactive={"power-card":"FLIP CARD","access-key":"UNLOCK","drop":"OPEN DROP","badge":"REVEAL BADGE","spotlight":"ACTIVATE SPOTLIGHT"}[id];document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop asset-modal-${id}" data-action="close-overlay"><div class="modal" role="dialog" aria-modal="true" onclick="event.stopPropagation()"><div class="modal-head"><div><div class="eyebrow">GAME ASSET · ${a.meaning}</div><h2>${a.name}</h2></div><button class="close-button" data-action="close-overlay">×</button></div><div class="asset-showcase ${id}" id="assetShowcase"><div class="asset-face">${assetImg(a,"eager","asset-modal-visual")}</div><div class="asset-back"><strong>${a.name}</strong><p>${a.description}</p><small>Reward · +100 XP</small></div></div><p style="color:var(--muted);line-height:1.65">${a.description}</p>${interactive?`<button class="btn btn-primary" data-action="activate-asset" data-asset-id="${id}">${interactive}</button>`:`<button class="btn btn-primary" data-action="close-overlay">Got it</button>`}</div></div>`}
function openPreviewMenu(){const s=state.students[0];document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop" data-action="close-overlay"><div class="modal preview-modal" onclick="event.stopPropagation()"><div class="modal-head"><div><div class="eyebrow">DEMO PREVIEW</div><h2>Preview as Student</h2></div><button class="close-button" data-action="close-overlay" aria-label="Закрыть">×</button></div><p>Выберите ученика. Режим просмотра не меняет его данные.</p><div class="preview-card">${avatarHtml(s)}<div><strong id="previewName">${escapeHtml(s.name)}</strong><small id="previewHandle">${escapeHtml(s.nickname)}</small></div><select class="form-control" id="previewStudentSelect" aria-label="Выбрать ученика">${state.students.map(x=>`<option value="${x.id}">${escapeHtml(x.name)} · ${escapeHtml(x.nickname)}</option>`).join("")}</select><button class="btn btn-primary" data-action="preview-selected">ПОСМОТРЕТЬ КАК УЧЕНИК</button></div></div></div>`}

function openPhoto(id){const s=studentById(id);uploadDraft={studentId:id,source:s.photo||null,zoom:1,x:50,y:50};document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop" data-action="close-overlay"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><div><div class="eyebrow">PRIVATE STUDENT MEDIA</div><h2>Фото · ${escapeHtml(s.name)}</h2></div><button class="close-button" data-action="close-overlay">×</button></div><label class="upload-zone"><input id="photoInput" type="file" accept="image/jpeg,image/png,image/webp" hidden><b>🖼 Выбрать JPG, PNG или WebP</b><br><small>до 8 MB · фото оптимизируется и EXIF удаляется</small></label><div id="cropArea">${photoCropHtml(uploadDraft.source)}</div></div></div>`}
function photoCropHtml(src){if(!src)return `<div class="empty-state"><strong>Фото пока не выбрано</strong>Будет использован безопасный monogram placeholder.</div>`;return `<div class="crop-layout"><div><div class="crop-stage" id="cropStage"><img src="${src}" alt="Crop preview"></div><label class="range-field"><span>Zoom</span><input type="range" min="1" max="2.5" value="${uploadDraft.zoom}" step=".05" data-crop="zoom"></label><label class="range-field"><span>По X</span><input type="range" min="0" max="100" value="${uploadDraft.x}" data-crop="x"></label><label class="range-field"><span>По Y</span><input type="range" min="0" max="100" value="${uploadDraft.y}" data-crop="y"></label></div><div class="crop-previews"><div><small>Карточка</small><div class="crop-preview round"><img src="${src}" alt="Round preview"></div></div><div><small>Профиль</small><div class="crop-preview square"><img src="${src}" alt="Square preview"></div></div></div></div><div class="modal-actions"><button class="btn btn-danger" data-action="remove-photo" data-id="${uploadDraft.studentId}">Remove</button><button class="btn btn-secondary" data-action="close-overlay">Cancel</button><button class="btn btn-primary" data-action="save-photo">Save photo</button></div>`}
function updateCropVisual(){document.querySelectorAll(".crop-stage img,.crop-preview img").forEach(img=>{img.style.setProperty("--zoom",uploadDraft.zoom);img.style.setProperty("--x",`${uploadDraft.x}%`);img.style.setProperty("--y",`${uploadDraft.y}%`)})}
function processPhoto(file){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type))return toast("Разрешены только JPG, PNG и WebP");if(file.size>8*1024*1024)return toast("Файл больше 8 MB");const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{if(img.width<200||img.height<200)return toast("Минимальный размер — 200×200 px");uploadDraft.source=reader.result;document.querySelector("#cropArea").innerHTML=photoCropHtml(uploadDraft.source)};img.src=reader.result};reader.readAsDataURL(file)}
function makeCroppedPhoto(callback){const img=new Image();img.onload=()=>{const size=512,canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=canvas.height=size;const scale=Math.max(size/img.width,size/img.height)*uploadDraft.zoom;const dw=img.width*scale,dh=img.height*scale,maxX=Math.max(0,dw-size),maxY=Math.max(0,dh-size),dx=-maxX*(uploadDraft.x/100),dy=-maxY*(uploadDraft.y/100);ctx.drawImage(img,dx,dy,dw,dh);callback(canvas.toDataURL("image/webp",.84))};img.src=uploadDraft.source}
function showLevelUp(s){if(!effectsOn())return;const el=document.createElement("div");el.className="level-up-overlay";el.innerHTML=`<span>LEVEL UP</span><strong>${s.level}</strong><small>${escapeHtml(s.name)}</small>`;document.body.append(el);setTimeout(()=>el.remove(),1500)}

document.addEventListener("click",e=>{
 const routeBtn=e.target.closest("[data-route]");if(routeBtn){go(routeBtn.dataset.route);return}
 const student=e.target.closest("[data-student]");if(student){route==="admin"?openStudent(student.dataset.student):(state.previewId=student.dataset.student,saveState(),go("profile"));return}
 const asset=e.target.closest("[data-asset]");if(asset){openAsset(asset.dataset.asset);return}
 const admin=e.target.closest("[data-admin-tab]");if(admin){adminTab=admin.dataset.adminTab;render();return}
 const btn=e.target.closest("[data-action]");if(!btn)return;const id=btn.dataset.id,action=btn.dataset.action;
 if(action==="open-admin")go("admin");
 if(action==="toggle-theme"){theme=theme==="dark"?"light":"dark";applyTheme();toast(`Тема: ${theme==="light"?'Light':'Dark'}`)}
 if(action==="close-overlay"){document.querySelector("#modalRoot").innerHTML="";document.body.classList.remove("spotlight-active")}
 if(action==="toggle-sound"){state.sound=!state.sound;saveState();toast(`Sound effects: ${state.sound?'On':'Off'}`)}
 if(action==="start-mission"){const s=viewer(),record=state.weekRecords[s.id][state.currentWeek-1];commit("Mission started",`${s.name} начал(а) Week ${state.currentWeek}`,()=>{s.weekStatus="In Progress";s.progress=Math.max(s.progress,25);record.status="In Progress";record.progress=s.progress;addHistory(s,"Mission started",`Week ${state.currentWeek} · ${weeks[state.currentWeek-1].title}`);state.feed.unshift({icon:"▶️",text:`${s.name} начал(а) ${weeks[state.currentWeek-1].title}`,time:"только что"})})}
 if(action==="view-week"){const w=weeks[Number(btn.dataset.week)-1];if(w.number>state.currentWeek)return toast("🔒 Эта неделя ещё закрыта");go("missions")}
 if(action==="event-info")toast("Season Kickoff · дата будет объявлена")
 if(action==="xp-modal")openXpModal(id,btn.dataset.amount||"");
 if(action==="save-xp"){const s=studentById(id),amount=Number(document.querySelector("#xpAmount").value),reason=document.querySelector("#xpReason").value,week=Number(document.querySelector("#xpWeek").value),oldLevel=s.level;if(!amount||!reason)return toast("Amount и Reason обязательны");commit("XP transaction",`${amount>0?'+':''}${amount} XP → ${s.name} · ${reason}`,()=>{s.transactions.push({id:crypto.randomUUID(),studentId:s.id,amount,reason,week,missionId:`week-${week}`,createdBy:"admin",date:new Date().toISOString()});s.level=Math.max(1,Math.floor(Math.max(0,totalXp(s))/500)+1);addHistory(s,"XP changed",`${amount>0?'+':''}${amount} XP · ${reason}`);if(s.level>oldLevel)addHistory(s,"LEVEL UP",`Level ${s.level}`);state.feed.unshift({icon:"⚡",text:`${s.name} получает ${amount>0?'+':''}${amount} XP`,time:"только что"})});document.querySelector("#modalRoot").innerHTML="";burstXp(amount,btn);if(s.level>oldLevel)showLevelUp(s)}
 if(action==="complete"){const s=studentById(id),week=Number(btn.dataset.week||state.currentWeek),w=weeks[week-1],record=state.weekRecords[id][week-1],already=(state.completions[id]||[]).includes(week);if(already)return toast("Эта миссия уже завершена");commit("Mission completed",`${s.name}: Week ${week} completed`,()=>{state.completions[id]=[...(state.completions[id]||[]),week];record.status="Completed";record.progress=100;if(week===state.currentWeek){s.progress=100;s.weekStatus="Completed"}addHistory(s,"Mission completed",`Week ${week} · ${w.title}`);state.feed.unshift({icon:"✅",text:`${s.name} завершил(а) ${w.title}`,time:"только что"})});confetti()}
 if(action==="asset-modal")openAssetPicker(id);
 if(action==="grant-asset"){const s=studentById(id),assetId=btn.dataset.assetId,a=assetById(assetId);commit("Asset granted",`${a.name} → ${s.name}`,()=>{if(!s.inventory.includes(assetId))s.inventory.push(assetId);if(assetId==="badge")s.featuredBadge=state.currentWeek===4?"Brave Speaker":"First Badge";if(assetId==="sticker"&&!s.stickers.includes("LEVEL UP"))s.stickers.push("LEVEL UP");if(assetId==="spotlight")s.spotlight=true;state.weekRecords[id][state.currentWeek-1].asset=assetId;addHistory(s,"Asset granted",a.name);state.feed.unshift({icon:assetId==="badge"?"🏅":"🎁",text:`${s.name} получает ${a.name}`,time:"только что"})});document.querySelector("#modalRoot").innerHTML="";confetti()}
 if(action==="streak-add"){const s=studentById(id);commit("Streak updated",`${s.name}: +1 Day`,()=>{s.streak++;s.longestStreak=Math.max(s.longestStreak,s.streak);addHistory(s,"Streak",`+1 day · total ${s.streak}`)})}
 if(action==="streak-reset"){const s=studentById(id);commit("Streak reset",`${s.name}: streak → 0`,()=>{s.streak=0;addHistory(s,"Streak reset","0 days")})}
 if(action==="streak-custom"){const s=studentById(id),value=prompt("Streak days",String(s.streak));if(value!==null&&!Number.isNaN(Number(value)))commit("Streak changed",`${s.name}: streak → ${value}`,()=>{s.streak=Math.max(0,Number(value));s.longestStreak=Math.max(s.longestStreak,s.streak)})}
 if(action==="save-student"){const s=studentById(id),week=Number(btn.dataset.week||state.currentWeek),record=state.weekRecords[id][week-1],name=document.querySelector("#studentName").value.trim(),nick=document.querySelector("#studentNick").value.trim(),progress=clamp(Number(document.querySelector("#studentProgress").value),0,100),status=document.querySelector("#studentStatus").value,privateNote=document.querySelector("#studentPrivateNote").value.trim(),feedback=document.querySelector("#studentFeedback").value.trim();commit("Student updated",`${s.name}: profile and Week ${week} saved`,()=>{s.name=name||s.name;s.nickname=nick||s.nickname;s.privateNote=privateNote;s.feedback=feedback;record.progress=progress;record.status=status;if(week===state.currentWeek){s.progress=progress;s.weekStatus=status}addHistory(s,"Profile updated",`Week ${week} · ${status} · ${progress}%`)});document.querySelector("#modalRoot").innerHTML=""}
 if(action==="matrix-cell")openStudent(id,Number(btn.dataset.week));
 if(action==="photo")openPhoto(id);
 if(action==="remove-photo"){const s=studentById(id);commit("Photo removed",`${s.name}: безопасный placeholder восстановлен`,()=>{delete s.photo;addHistory(s,"Photo removed","Placeholder restored")});document.querySelector("#modalRoot").innerHTML=""}
 if(action==="save-photo"&&uploadDraft?.source){makeCroppedPhoto(data=>{const s=studentById(uploadDraft.studentId);commit("Photo updated",`${s.name}: фото обновлено`,()=>{s.photo=data;addHistory(s,"Photo updated","Private local image replaced")});document.querySelector("#modalRoot").innerHTML=""})}
 if(action==="preview-menu")openPreviewMenu();
 if(action==="preview-student"){state.previewId=id;saveState();document.querySelector("#modalRoot").innerHTML="";go("home")}
 if(action==="preview-selected"){state.previewId=document.querySelector("#previewStudentSelect").value;saveState();document.querySelector("#modalRoot").innerHTML="";go("home")}
 if(action==="exit-preview"){state.previewId=null;saveState();go("admin")}
 if(action==="undo"&&lastUndo){lastUndo();lastUndo=null}
 if(action==="reset-season")openResetSeason();
 if(action==="confirm-reset-season"){if(document.querySelector("#resetPhrase").value!=="RESET SEASON")return toast("Введите RESET SEASON точно");const profiles=state.students.map(s=>({id:s.id,name:s.name,nickname:s.nickname,photo:s.photo})),fresh=seedState();fresh.students.forEach(s=>Object.assign(s,profiles.find(p=>p.id===s.id)));state=fresh;saveState();document.querySelector("#modalRoot").innerHTML="";render();toast("Season reset · results are zero")}
 if(action==="new-mission")openMissionEditor();
 if(action==="edit-mission")openMissionEditor(id);
 if(action==="save-mission"){const existing=state.missions.find(x=>x.id===id),data={id:id||`mission-${crypto.randomUUID()}`,week:Number(document.querySelector("#missionWeek").value),title:document.querySelector("#missionTitle").value.trim(),description:document.querySelector("#missionDescription").value.trim(),instructions:document.querySelector("#missionInstructions").value.trim(),baseXp:Number(document.querySelector("#missionXp").value),bonusXp:Number(document.querySelector("#missionBonusXp").value),submissionType:document.querySelector("#missionSubmission").value,active:true,archived:false};if(!data.title)return toast("Mission title is required");commit(existing?"Mission updated":"Mission created",data.title,()=>{existing?Object.assign(existing,data):state.missions.push(data)});document.querySelector("#modalRoot").innerHTML=""}
 if(action==="duplicate-mission"){const m=state.missions.find(x=>x.id===id);commit("Mission duplicated",`${m.title} copy`,()=>state.missions.push({...structuredClone(m),id:`mission-${crypto.randomUUID()}`,title:`${m.title} Copy`}))}
 if(action==="toggle-mission"){const m=state.missions.find(x=>x.id===id);commit("Mission visibility changed",m.title,()=>m.active=!m.active)}
 if(action==="activate-asset"){const showcase=document.querySelector("#assetShowcase"),assetId=btn.dataset.assetId;showcase.classList.add("activated");btn.textContent=assetId==="access-key"?"SECRET UNLOCKED":assetId==="drop"?"REWARD REVEALED":assetId==="power-card"?"USED":assetId==="badge"?"NEW BADGE":"SPOTLIGHT ON";if(assetId==="spotlight")document.body.classList.add("spotlight-active");confetti()}
 if(action.startsWith("bulk-")){const ids=[...document.querySelectorAll("[data-select-student]:checked")].map(x=>x.dataset.selectStudent);if(!ids.length)return toast("Сначала выберите учеников");if(action==="bulk-complete")commit("Bulk complete",`${ids.length} students · Week ${state.currentWeek}`,()=>ids.forEach(studentId=>{const s=studentById(studentId),record=state.weekRecords[studentId][state.currentWeek-1];if(!state.completions[studentId].includes(state.currentWeek))state.completions[studentId].push(state.currentWeek);record.status="Completed";record.progress=100;s.weekStatus="Completed";s.progress=100;addHistory(s,"Mission completed",`Bulk · Week ${state.currentWeek}`)}));else if(action==="bulk-xp"){const amount=Number(prompt("XP amount for selected students","50")),reason=amount?prompt("Reason (required)","Teacher Bonus"):null;if(amount&&reason)commit("Bulk XP",`${amount>0?'+':''}${amount} XP · ${ids.length} students`,()=>ids.forEach(studentId=>{const s=studentById(studentId);s.transactions.push({id:crypto.randomUUID(),studentId,amount,reason,week:state.currentWeek,createdBy:"admin",date:new Date().toISOString()});s.level=Math.max(1,Math.floor(Math.max(0,totalXp(s))/500)+1);addHistory(s,"Bulk XP",`${amount>0?'+':''}${amount} · ${reason}`)}))}else if(action==="bulk-asset"){const assetId=prompt(`Asset id: ${assets.map(a=>a.id).join(', ')}`,"ticket");if(assetById(assetId))commit("Bulk asset",`${assetId} · ${ids.length} students`,()=>ids.forEach(studentId=>{const s=studentById(studentId);if(!s.inventory.includes(assetId))s.inventory.push(assetId);addHistory(s,"Bulk asset",assetById(assetId).name)}))}else commit("Bulk reset",`${ids.length} students`,()=>ids.forEach(studentId=>{const s=studentById(studentId);s.weekStatus="Not Started";s.progress=0;state.weekRecords[studentId][state.currentWeek-1]={week:state.currentWeek,status:"Not Started",progress:0,asset:null}}))}
});

document.addEventListener("change",e=>{
 if(e.target.id==="photoInput")processPhoto(e.target.files[0]);
 if(e.target.id==="previewStudentSelect"){const s=studentById(e.target.value),card=document.querySelector(".preview-card");card.querySelector(".avatar").outerHTML=avatarHtml(s);document.querySelector("#previewName").textContent=s.name;document.querySelector("#previewHandle").textContent=s.nickname}
 const field=e.target.dataset.field;if(field){const s=studentById(e.target.dataset.id),value=field==="progress"?clamp(Number(e.target.value),0,100):e.target.value;commit("Tracker updated",`${s.name}: ${field} → ${value}`,()=>{s[field]=value;const record=state.weekRecords[s.id][state.currentWeek-1];if(field==="progress")record.progress=value;if(field==="weekStatus")record.status=value;addHistory(s,"Tracker updated",`${field} → ${value}`)})}
 const setting=e.target.dataset.setting;if(setting){let value=e.target.value;if(setting==="theme"){theme=value;applyTheme();render();return}if(["sound","particlesEnabled","leaderboardEnabled"].includes(setting))value=value==="true";if(setting==="currentWeek"||setting==="crewGoal")value=Number(value);commit("Setting changed",`${setting} → ${value}`,()=>{state[setting]=value;if(setting==="currentWeek")state.students.forEach(s=>{const r=state.weekRecords[s.id][value-1];s.weekStatus=r.status;s.progress=r.progress})});applyPreferences()}
});
document.addEventListener("input",e=>{const key=e.target.dataset.crop;if(!key)return;uploadDraft[key]=Number(e.target.value);updateCropVisual()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelector("#modalRoot").innerHTML="";if((e.key==="Enter"||e.key===" ")&&e.target.matches("[data-student]")){e.preventDefault();e.target.click()}});

function applyPreferences(){document.body.dataset.effects=state.effectsMode;document.body.classList.toggle("particles-off",!state.particlesEnabled);document.body.classList.toggle("motion-off",state.effectsMode==="off")}
function setupEnhancements(){if(!effectsOn())return;document.querySelectorAll(".panel,.section-head,.week-card").forEach(el=>el.classList.add("reveal-ready"));if("IntersectionObserver" in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("revealed");observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll(".reveal-ready").forEach(el=>observer.observe(el))}else document.querySelectorAll(".reveal-ready").forEach(el=>el.classList.add("revealed"))}
document.addEventListener("pointermove",e=>{if(!fullEffects()||!matchMedia("(pointer:fine)").matches)return;const card=e.target.closest(".tilt-card,.week-card,.asset-card");if(!card)return;const r=card.getBoundingClientRect(),rx=((e.clientY-r.top)/r.height-.5)*-3,ry=((e.clientX-r.left)/r.width-.5)*3;card.style.setProperty("--tilt-x",`${rx}deg`);card.style.setProperty("--tilt-y",`${ry}deg`)});
document.addEventListener("pointerout",e=>{const card=e.target.closest(".tilt-card,.week-card,.asset-card");if(card&&!card.contains(e.relatedTarget)){card.style.removeProperty("--tilt-x");card.style.removeProperty("--tilt-y")}});
document.addEventListener("error",e=>{if(e.target instanceof HTMLImageElement&&e.target.hasAttribute("data-fallback")){e.target.hidden=true;e.target.nextElementSibling?.classList.add("show")}},true);

const hash=location.hash.slice(1);if(location.pathname.startsWith("/admin")||hash==="admin")route="admin";else if(["home","challenge","missions","crew","events","leaderboard","feed","profile"].includes(hash))route=hash;
applyTheme();render();
